### PR TITLE
make system prompt configurable by caller

### LINKED ISSUE #7: Custom system prompt?
Hi, thanks for making this small Neovim plugin. It'd be great if I can customize the system prompt directly from `init.lua`. I'm going to fork and play around with it, and I'll make a PR if I get a thumbs up :)

### PR DESCRIPTION
**Pull request by pixqc**
fixes #7

### CODE REVIEW

**Comment by pixqc** [comment]
Currently uses the same system prompt for both `replace=true` and `replace=false` (I think). I've been testing it for the past couple hours and it works fine

**Review by melbaldove — CHANGES_REQUESTED** [review]
@pixqc might aswell make the `replace_prompt` configurable :D

**Comment by pixqc** [comment]
I think it's better if it's a separate PR, what do you think?

**Comment by melbaldove** [comment]
tbh its fine in this PR

**Comment by pixqc** [comment]
image

image

Works now! Looks good?

**Review by melbaldove — APPROVED** [review]
LGTM!

**Pull request merged**
