### PR TITLE
Switched from nio to plenary and added model picker

### PR DESCRIPTION
**Pull request by RussianStar**
I had issues with nio on windows and also with getting an api keys from openai/anthropic. This PR is my workaround for both solutions.

- I switched from nio to plenary for the task handling 
- I use openrouter as the llm provider, this also makes switching out the model easier

I also added a fuzzy finder for picking the model, so changing is effortless. I tested with some models, mainly the big ones and had no problems. 

Not sure if a PR is the correct format for this and I am aware that it includes quite some changes and maybe also a direction you dont want to go. But I spend too long trying to fix it for my setup with nio to just throw it away, maybe it helps someone in the future

### CODE REVIEW

**Comment by melbaldove** [comment]
@RussianStar tbh i shouldve used plenary in the first place so im open to merging that improvement if you want to split your PR. openrouter doesnt fit my workflow. i only mainly use two models. one fast (groq), and the big guns (either gpt4o or sonnet)

**Comment by RussianStar** [comment]
ok, ill split the two changes and update this branch

**Comment by yacineMTB** [comment]
FYI, dropping in here to say I did the same thing (nio would deadlock my editor). But I also dropped a ton of breaking changes and basically just spun off my own fork

https://github.com/yacineMTB/dingllm.nvim/blob/master/lua/dingllm.lua

Hope it's useful!

**Comment by melbaldove** [comment]
switched to plenary 5f1550a748069e46d64fca3234512c249c56fc18

**Pull request closed without merging**
